### ISSUE TITLE
Breaking change in linkifyjs 4.3.2 if linkify-react is on older version

### ISSUE THREAD

**Issue by joshzivot** [nfrasser/linkifyjs#520]
This error occurred in our app after upgrading linkifyjs to 4.3.2 –

`Uncaught TypeError: linkifyjs__WEBPACK_IMPORTED_MODULE_1__.options.assign is not a function`

linkify-react was still on 4.3.1 when this occurred, and upgrading to 4.3.2 fixed the issue. However, I would not expect a single patch version change to cause a fatal error.

Looking at the 4.3.2 change, it seems this occurred because the "assign" export was removed from linkifyjs in 4.3.2, so if an older version of linkify-react was being used, it's trying to import/use that function that no longer exists.

Thank you!

**Comment by Cav19** [comment]
I also just ran into a similar issue. My `package.json` file was using `4.0.2` and, critically, I didn't receive the "assign" export error when developing locally. I only encountered errors when working in deployed environments, making it a bit trick to track down. 

The error message also showed as `assign is not a function` for me. The upgrade to version `4.3.2` fixed the problem for me but I only tried that after a fair bit of trial and error! Given that the upgrade _fixed_ the issue for me, it may have been stemming from a different dependency but wanted to add my experience to the issue anyway.

**Comment by nfrasser** [comment]
Hey @joshzivot and @Cav19 , thanks very much for reporting. In the latest release, I've locked the `linkifyjs` requirement for `linkify-react` to have the same version (`==v4.3.3` instead of `^4.0.0`). This should prevent issues like this in the future. My apologies for the break!
